version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db 
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
volumes:
  postgres_db: